In [80]:
#Import
import numpy

In [81]:
numpy.__version__

'1.18.5'

In [82]:
import numpy as np
#numpy.func

In [83]:
np.__version__

'1.18.5'

In [84]:
np.array

<function numpy.array>

In [85]:
np?

### The Basics

In [86]:
a = np.array([1,2,3,4])
print(a,type(a))

[1 2 3 4] <class 'numpy.ndarray'>


In [87]:
type(a)

numpy.ndarray

In [88]:
tuple_1 = (1,2,3,4)
b = np.array(tuple_1)
print(b,type(b))

[1 2 3 4] <class 'numpy.ndarray'>


In [89]:
tuple_1 = (1,2,3,4)
b = np.array(tuple_1, dtype = "float")
print(b,type(b))

[1. 2. 3. 4.] <class 'numpy.ndarray'>


In [90]:
#Dtype
a = np.array([1,2,3,4], dtype='int32')
print(a)

[1 2 3 4]


In [91]:
b = np.array([[6.0,5.0,4.0],[9.0,8.0,7.0]])
print(b)

[[6. 5. 4.]
 [9. 8. 7.]]


In [92]:
a

array([1, 2, 3, 4])

In [93]:
# Get Dimension
a.ndim

1

In [94]:
b.ndim

2

In [95]:
b

array([[6., 5., 4.],
       [9., 8., 7.]])

In [96]:
# Get Shape
b.shape

(2, 3)

In [97]:
# Get Type
a.dtype

dtype('int32')

In [98]:
b.dtype

dtype('float64')

In [99]:
# Get Size 
a.itemsize

4

In [100]:
a

array([1, 2, 3, 4])

In [101]:
# Get total size (memory)
a.nbytes

16

In [102]:
# Get number of elements
a.size

4

In [103]:
b.size

6

In [104]:
print(b.ndim,b.shape,b.dtype,b.size)

2 (2, 3) float64 6


---

### Indexing & Slicing

In [105]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [106]:
a[1,4]

11

In [107]:
# Get a specific element [r, c]
a[1, 5]

12

In [108]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6])

In [ ]:
a[1,:]

In [ ]:
a[:,2]

In [ ]:
a

In [ ]:
# Get a specific column
a[:, 3]

In [ ]:
a[:,1:3]

In [ ]:
a

In [ ]:
# [startindex:endindex:stepsize]
a[0, 1:-1:2]

In [ ]:
a

In [ ]:
a[1,4] = 99
print(a)

### 3-d Array example

In [ ]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

In [ ]:
b.ndim

In [ ]:
b.shape

In [ ]:
# Get specific element (work outside in)
b[0,1,1]

---

### Arrays with Initialized values

In [109]:
# All 0s matrix
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [110]:
np.zeros([4,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [111]:
np.zeros(shape = [4,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [112]:
np.zeros(shape = [4,2],dtype = "complex")

array([[0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j]])

In [114]:
# All 1s matrix
np.ones((3,2), dtype='int32')

array([[1, 1],
       [1, 1],
       [1, 1]])

In [113]:
# All 1s matrix
np.ones((4,3,2), dtype='int32')

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

In [ ]:
# Any other number
np.full(shape=(3,2),fill_value= 99)

In [ ]:
np.full((4,5),100)

In [ ]:
b

In [ ]:
# Any other number (full_like)
np.full_like(b, 4)

In [ ]:
# Random decimal numbers
np.random.rand(4,2)

In [ ]:
# Random Integer values
np.random.randint(-10,10, size=(3,3))

In [ ]:
# The identity matrix
np.identity(4)

In [ ]:
# Repeat an array
arr = np.array([[1,2,3,4]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

---

##### copying arrays!!!

In [4]:
a = np.array([1,2,3])
print(a)
b = a
b[0] = 99

print(a)
print(b)

[1 2 3]
[99  2  3]
[99  2  3]


In [5]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 99

print(a)
print(b)

[1 2 3]
[99  2  3]


---

### Mathematics

In [6]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [7]:
a + 2

array([3, 4, 5, 6])

In [8]:
a - 2

array([-1,  0,  1,  2])

In [9]:
a * 2

array([2, 4, 6, 8])

In [10]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [11]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [12]:
a - b

array([0, 2, 2, 4])

In [13]:
a*b

array([1, 0, 3, 0])

In [14]:
a/b

<ipython-input-14-aae42d317509>:1: RuntimeWarning: divide by zero encountered in true_divide
  a/b


array([ 1., inf,  3., inf])

In [15]:
a**b

array([1, 1, 3, 1], dtype=int32)

In [16]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [17]:
# Take the cosine
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [18]:
np.sin(b)

array([0.84147098, 0.        , 0.84147098, 0.        ])

In [19]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

##### Linear Algebra

In [20]:
a = np.ones((3,5))
print(a)

b = np.full((5,4), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [22]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# determinant
c = np.identity(3)
np.linalg.det(c)

1.0

Reference docs:

(https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

    - Determinant
    - Trace
    - Singular Vector Decomposition
    - Eigenvalues
    - Matrix Norm
    - Inverse, etc.

---

### Shape Modification Arrays

In [23]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(a.shape)

b = a.reshape((4,2)) #array_name.reshape((new_shape))
print(b)
print(b.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


In [24]:
np.reshape(a,(4,2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [25]:
a.size

8

In [26]:
b = np.reshape(a,(3,3))
print(b)
b.shape

ValueError: cannot reshape array of size 8 into shape (3,3)

In [27]:
#resize
print(a)
a.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [28]:
b = np.resize(a,(6,2))
print(b)
b.shape

[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [1 2]
 [3 4]]


(6, 2)

In [29]:
# Vertically stacking vectors
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [30]:
a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.array([[7,8,9],[10,11,12]])
np.vstack([a1,a2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [31]:
# Horizontal  stack
h1 = np.ones((2,5))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0.]])

In [32]:
a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.array([[7,8,9],[10,11,12]])
np.hstack([a1,a2])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

---

#### `np.arange()`

In [33]:
#start,stop,step size
np.arange(5)

array([0, 1, 2, 3, 4])

In [34]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(1,5)#step = 1

array([1, 2, 3, 4])

In [36]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [37]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [38]:
np.arange(1,10,1).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##### Relational Operators on Arrays

In [39]:
x = np.array([1, 2, 3, 4, 5])

In [40]:
x < 3  # less than

array([ True,  True, False, False, False])

In [41]:
x <= 3  # less than or equal

array([ True,  True,  True, False, False])

In [42]:
#Operation , then comparison
(2 * x) == (x ** 2)

array([False,  True, False, False, False])

In [43]:
x = np.random.randint(-10,10,size=(4,5))
x

array([[  1,  -7,  -3, -10,  -4],
       [ -6,  -8,  -6,   1,   2],
       [  9,   6,  -7,   3,   8],
       [  0,   7,  -6,  -1,  -4]])

In [44]:
x>3

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True, False, False,  True],
       [False,  True, False, False, False]])

In [46]:
x

array([[  1,  -7,  -3, -10,  -4],
       [ -6,  -8,  -6,   1,   2],
       [  9,   6,  -7,   3,   8],
       [  0,   7,  -6,  -1,  -4]])

In [45]:
np.sum(x)

-25

In [47]:
np.sum(x,axis=0)

array([  4,  -2, -22,  -7,   2])

In [48]:
np.sum(x,axis=1)

array([-23, -17,  19,  -4])

In [49]:
np.max(x)

9

In [50]:
np.min(x)

-10

In [52]:
x

array([[  1,  -7,  -3, -10,  -4],
       [ -6,  -8,  -6,   1,   2],
       [  9,   6,  -7,   3,   8],
       [  0,   7,  -6,  -1,  -4]])

In [51]:
np.sum(x > 2)

5

In [53]:
# how many values less than 2 in each row?
np.sum(x < 2, axis=1)

array([5, 4, 1, 4])

---

##### Boolean Masking

In [54]:
x

array([[  1,  -7,  -3, -10,  -4],
       [ -6,  -8,  -6,   1,   2],
       [  9,   6,  -7,   3,   8],
       [  0,   7,  -6,  -1,  -4]])

In [57]:
x > 5

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True, False, False,  True],
       [False,  True, False, False, False]])

In [58]:
x[x>5]

array([9, 6, 8, 7])

---

### Broadcasting

In [63]:
x = np.ones((5,2)) # 5,2
y = np.arange(2) # (2)
x*y

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [64]:
x = np.ones((5,3))
y = np.arange(2)
x*y

ValueError: operands could not be broadcast together with shapes (5,3) (2,) 

In [65]:
#case 1
x = np.ones((3,2)) # 5,2
y = np.arange(2) # (2)
x.shape,y.shape

((3, 2), (2,))

In [66]:
x*y

array([[0., 1.],
       [0., 1.],
       [0., 1.]])

In [67]:
#case 2
x = np.ones((3,2)) # 
y = np.arange(3) # (2)
x.shape,y.shape

((3, 2), (3,))

In [68]:
x*y

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [69]:
#case 3
x = np.ones((3,5,7)) # 
y = np.arange(7) # (2)
x.shape,y.shape

((3, 5, 7), (7,))

In [71]:
x*y, (x*y).shape

(array([[[0., 1., 2., 3., 4., 5., 6.],
         [0., 1., 2., 3., 4., 5., 6.],
         [0., 1., 2., 3., 4., 5., 6.],
         [0., 1., 2., 3., 4., 5., 6.],
         [0., 1., 2., 3., 4., 5., 6.]],
 
        [[0., 1., 2., 3., 4., 5., 6.],
         [0., 1., 2., 3., 4., 5., 6.],
         [0., 1., 2., 3., 4., 5., 6.],
         [0., 1., 2., 3., 4., 5., 6.],
         [0., 1., 2., 3., 4., 5., 6.]],
 
        [[0., 1., 2., 3., 4., 5., 6.],
         [0., 1., 2., 3., 4., 5., 6.],
         [0., 1., 2., 3., 4., 5., 6.],
         [0., 1., 2., 3., 4., 5., 6.],
         [0., 1., 2., 3., 4., 5., 6.]]]),
 (3, 5, 7))

In [72]:
#case 4
x = np.ones((3,8,1)) # 
y = np.arange(72).reshape(8,9) # (2)
x.shape,y.shape

((3, 8, 1), (8, 9))

In [73]:
x+y,(x+y).shape

(array([[[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14., 15., 16., 17., 18.],
         [19., 20., 21., 22., 23., 24., 25., 26., 27.],
         [28., 29., 30., 31., 32., 33., 34., 35., 36.],
         [37., 38., 39., 40., 41., 42., 43., 44., 45.],
         [46., 47., 48., 49., 50., 51., 52., 53., 54.],
         [55., 56., 57., 58., 59., 60., 61., 62., 63.],
         [64., 65., 66., 67., 68., 69., 70., 71., 72.]],
 
        [[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14., 15., 16., 17., 18.],
         [19., 20., 21., 22., 23., 24., 25., 26., 27.],
         [28., 29., 30., 31., 32., 33., 34., 35., 36.],
         [37., 38., 39., 40., 41., 42., 43., 44., 45.],
         [46., 47., 48., 49., 50., 51., 52., 53., 54.],
         [55., 56., 57., 58., 59., 60., 61., 62., 63.],
         [64., 65., 66., 67., 68., 69., 70., 71., 72.]],
 
        [[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14., 15., 16

In [74]:
#case 5
x = np.ones((5,1)) # 
y = np.arange(25).reshape(5,5) # (2)
x.shape,y.shape

((5, 1), (5, 5))

In [75]:
x+y,(x+y).shape

(array([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.],
        [16., 17., 18., 19., 20.],
        [21., 22., 23., 24., 25.]]),
 (5, 5))